site_name: RcBoatController
site_url: https://github.com/djtremolo/RcBoatController
site_description: Project documentation for RcBoatController
site_author: djtremolo@gmail.com

docs_dir: 'doc'
nav:
    - Home: README.md